import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { setupWorkspace } from "./workspace-setup.js";

export type McuProfile = "arduino" | "esp32-arduino" | "esp32-idf";
export type McuTemplate = "minimal" | "wifi" | "ble" | "webserver" | "custom";

export type McuSetupOptions = {
  workspace: string;
  profile: McuProfile;
  board?: string;
  template?: McuTemplate;
  overwrite?: boolean;
};

export type McuSetupResult = {
  profile: McuProfile;
  board: string;
  template: McuTemplate;
  created: string[];
  configPath: string;
};

export const MCU_DEFAULTS: Record<McuProfile, { board: string; template: McuTemplate }> = {
  arduino: { board: "uno", template: "minimal" },
  "esp32-arduino": { board: "esp32dev", template: "minimal" },
  "esp32-idf": { board: "esp32", template: "minimal" },
};

export function listMcuProfiles(): McuProfile[] {
  return ["arduino", "esp32-arduino", "esp32-idf"];
}

export function getMcuProfileSummary(profile: McuProfile): { board: string; template: McuTemplate; description: string } {
  const defaults = MCU_DEFAULTS[profile];
  const descriptions: Record<McuProfile, string> = {
    arduino: "Classic Arduino sketch project for general MCU prototypes.",
    "esp32-arduino": "ESP32 project using the Arduino framework and PlatformIO.",
    "esp32-idf": "ESP32 project using the native ESP-IDF toolchain.",
  };

  return {
    ...defaults,
    description: descriptions[profile],
  };
}

export async function isMcuWorkspaceSetup(workspace: string): Promise<boolean> {
  try {
    const configPath = path.join(workspace, ".rig", "plugins", "mcu.json");
    const statResult = await stat(configPath);
    return statResult.isFile();
  } catch {
    return false;
  }
}

async function shouldWrite(filePath: string, overwrite = false): Promise<boolean> {
  try {
    await stat(filePath);
    return overwrite;
  } catch {
    return true;
  }
}

function renderArduinoSketch(board: string, template: McuTemplate): string {
  const templateIntro = `// Generated by RIG MCU plugin\n// Board: ${board}\n// Template: ${template}\n`;

  if (template === "wifi") {
    return `${templateIntro}\nvoid setup() {\n  Serial.begin(115200);\n  delay(1000);\n  Serial.println("WiFi sketch ready");\n}\n\nvoid loop() {\n  Serial.println("Running WiFi template");\n  delay(1000);\n}\n`;
  }

  if (template === "webserver") {
    return `${templateIntro}\nvoid setup() {\n  Serial.begin(115200);\n  Serial.println("Web server template ready");\n}\n\nvoid loop() {\n  Serial.println("Serving loop");\n  delay(1000);\n}\n`;
  }

  return `${templateIntro}\nvoid setup() {\n  Serial.begin(115200);\n  Serial.println("Arduino sketch booted");\n}\n\nvoid loop() {\n  Serial.println("Running Arduino template");\n  delay(1000);\n}\n`;
}

function renderEsp32PioConfig(board: string, template: McuTemplate): string {
  const templateNote = `; Generated by RIG MCU plugin\n; Board: ${board}\n; Template: ${template}\n`;
  return `${templateNote}\n[platformio]\nsrc_dir = src\n\n[env:${board}]\nplatform = espressif32\nboard = ${board}\nframework = arduino\nmonitor_speed = 115200\n`;
}

function renderEsp32ArduinoMain(): string {
  return `#include <Arduino.h>\n\nvoid setup() {\n  Serial.begin(115200);\n  delay(1000);\n  Serial.println("ESP32 Arduino booted");\n}\n\nvoid loop() {\n  Serial.println("ESP32 Arduino template running");\n  delay(1000);\n}\n`;
}

function renderEsp32IdfMain(): string {
  return `#include <stdio.h>\n\nvoid app_main(void) {\n  printf("ESP-IDF template initialized\\n");\n  while (1) {\n    printf("ESP32 IDF loop running\\n");\n    for (volatile int i = 0; i < 1000000; ++i) { }\n  }\n}\n`;
}

function renderEsp32IdfCmake(): string {
  return `cmake_minimum_required(VERSION 3.16)\ninclude($ENV{IDF_PATH}/tools/cmake/project.cmake)\nproject(rig_mcu)\n`;
}

function renderEsp32IdfMainCmake(): string {
  return `idf_component_register(SRCS "main.cpp" INCLUDE_DIRS "")\n`;
}

function renderMcuReadme(profile: McuProfile, board: string, template: McuTemplate): string {
  return `# ${profile} MCU Project\n\nThis project was scaffolded by RIG's MCU plugin.\n\n- Profile: ${profile}\n- Board: ${board}\n- Template: ${template}\n\n## Notes\n\nUse the plugin's build/flash workflow before uploading firmware to hardware.\n`;
}

export function resolveMcuBoard(profile: McuProfile, board?: string): string {
  return board ?? MCU_DEFAULTS[profile].board;
}

export function resolveMcuTemplate(profile: McuProfile, template?: McuTemplate): McuTemplate {
  return template ?? MCU_DEFAULTS[profile].template;
}

export async function setupMcuWorkspace(options: McuSetupOptions): Promise<McuSetupResult> {
  const workspace = path.resolve(options.workspace);
  const profile = options.profile;
  const defaults = MCU_DEFAULTS[profile];
  const board = resolveMcuBoard(profile, options.board);
  const template = resolveMcuTemplate(profile, options.template);

  await setupWorkspace(workspace);

  const pluginDir = path.join(workspace, ".rig", "plugins");
  await mkdir(pluginDir, { recursive: true });
  const configPath = path.join(pluginDir, "mcu.json");
  const config = {
    enabled: true,
    profile,
    board,
    template,
    createdAt: new Date().toISOString(),
  };

  await writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");

  const created: string[] = [".rig/plugins/mcu.json"];

  if (profile === "arduino") {
    const sketchPath = path.join(workspace, "sketch.ino");
    if (await shouldWrite(sketchPath, options.overwrite)) {
      await writeFile(sketchPath, renderArduinoSketch(board, template), "utf8");
      created.push("sketch.ino");
    }

    const readmePath = path.join(workspace, "README.mcu.md");
    if (await shouldWrite(readmePath, options.overwrite)) {
      await writeFile(readmePath, renderMcuReadme(profile, board, template), "utf8");
      created.push("README.mcu.md");
    }
  }

  if (profile === "esp32-arduino") {
    const pioPath = path.join(workspace, "platformio.ini");
    if (await shouldWrite(pioPath, options.overwrite)) {
      await writeFile(pioPath, renderEsp32PioConfig(board, template), "utf8");
      created.push("platformio.ini");
    }

    const srcDir = path.join(workspace, "src");
    await mkdir(srcDir, { recursive: true });
    const mainPath = path.join(srcDir, "main.cpp");
    if (await shouldWrite(mainPath, options.overwrite)) {
      await writeFile(mainPath, renderEsp32ArduinoMain(), "utf8");
      created.push("src/main.cpp");
    }

    const readmePath = path.join(workspace, "README.mcu.md");
    if (await shouldWrite(readmePath, options.overwrite)) {
      await writeFile(readmePath, renderMcuReadme(profile, board, template), "utf8");
      created.push("README.mcu.md");
    }
  }

  if (profile === "esp32-idf") {
    const cmakePath = path.join(workspace, "CMakeLists.txt");
    if (await shouldWrite(cmakePath, options.overwrite)) {
      await writeFile(cmakePath, renderEsp32IdfCmake(), "utf8");
      created.push("CMakeLists.txt");
    }

    const mainDir = path.join(workspace, "main");
    await mkdir(mainDir, { recursive: true });
    const mainCmakePath = path.join(mainDir, "CMakeLists.txt");
    if (await shouldWrite(mainCmakePath, options.overwrite)) {
      await writeFile(mainCmakePath, renderEsp32IdfMainCmake(), "utf8");
      created.push("main/CMakeLists.txt");
    }

    const mainFilePath = path.join(mainDir, "main.cpp");
    if (await shouldWrite(mainFilePath, options.overwrite)) {
      await writeFile(mainFilePath, renderEsp32IdfMain(), "utf8");
      created.push("main/main.cpp");
    }

    const sdkConfigPath = path.join(workspace, "sdkconfig.defaults");
    if (await shouldWrite(sdkConfigPath, options.overwrite)) {
      await writeFile(sdkConfigPath, "CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y\n", "utf8");
      created.push("sdkconfig.defaults");
    }

    const readmePath = path.join(workspace, "README.mcu.md");
    if (await shouldWrite(readmePath, options.overwrite)) {
      await writeFile(readmePath, renderMcuReadme(profile, board, template), "utf8");
      created.push("README.mcu.md");
    }
  }

  return {
    profile,
    board,
    template,
    created,
    configPath,
  };
}

export async function loadMcuConfig(workspace: string): Promise<Record<string, unknown> | undefined> {
  try {
    const configPath = path.join(workspace, ".rig", "plugins", "mcu.json");
    const content = await readFile(configPath, "utf8");
    return JSON.parse(content);
  } catch {
    return undefined;
  }
}

export async function initializeMcuWorkspace(
  workspace: string,
  options: Partial<Pick<McuSetupOptions, "profile" | "board" | "template" | "overwrite">> = {},
): Promise<McuSetupResult | undefined> {
  if (await isMcuWorkspaceSetup(workspace)) {
    return undefined;
  }

  const profile = options.profile ?? "esp32-arduino";
  const board = resolveMcuBoard(profile, options.board);
  const template = resolveMcuTemplate(profile, options.template);

  return setupMcuWorkspace({
    workspace,
    profile,
    board,
    template,
    overwrite: options.overwrite,
  });
}
